-- Durable per-student page position for the native document reader.
-- Safe to run repeatedly.
CREATE TABLE IF NOT EXISTS document_reading_progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    document_id INTEGER NOT NULL REFERENCES document(id),
    page_num INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_document_reading_progress_user_document UNIQUE (user_id, document_id),
    CONSTRAINT ck_document_reading_progress_page_nonnegative CHECK (page_num >= 0)
);

CREATE INDEX IF NOT EXISTS ix_document_reading_progress_user_id
    ON document_reading_progress (user_id);
CREATE INDEX IF NOT EXISTS ix_document_reading_progress_document_id
    ON document_reading_progress (document_id);
