import { useEffect, useState } from 'react'

type Props={onExit:()=>void}
type Opp={id:number;title:string;status:string;view_count:number;organic_free_impression_cap:number;organic_free_cap_reached_at?:string|null;sponsored_impressions:number;sponsored_clicks:number;sponsored_applications:number}
type Camp={id:number;opportunity_id?:number|null;name:string;opportunity_title:string;objective:string;placement:string;status:string;budget_kes:number;funded_amount_minor:number;delivered_impressions:number;delivered_clicks:number;delivered_applications:number;push_delivered:number}
type Dash={organisation:any;plan:any;ad_budget:any;active_sponsorships:number;opportunities:Opp[];campaigns:Camp[];free_policy:any}
const N='#0B1437', G='#C9A84C', M='#77809A', BG='#F5F6FA'
const money=(n:number)=>'KES '+(Number(n||0)/100).toLocaleString(undefined,{maximumFractionDigits:0})
async function req<T>(p:string,o:RequestInit={}):Promise<T>{const r=await fetch(p,{credentials:'include',...o,headers:{'Content-Type':'application/json',...(o.headers||{})}});const b:any=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||'Request failed');return b}

export default function PremiumOrganisationPortal({onExit}:Props){
 const [csrf,setCsrf]=useState(''),[orgId,setOrgId]=useState<number|null>(null),[dash,setDash]=useState<Dash|null>(null),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<any>(null),[analytics,setAnalytics]=useState<any>(null),[payments,setPayments]=useState<any>({payments:[],invoices:[]}),[kyc,setKyc]=useState<any[]>([]),[busy,setBusy]=useState(false),[sponsor,setSponsor]=useState<any>(null),[campaignForm,setCampaignForm]=useState({objective:'reach',placement:'feed',budget:'5000',duration:'30'})
 const load=async(id:number)=>{try{const m=await req<any>('/me');setCsrf(m.csrf_token||'');const [d,p,k]=await Promise.all([req<Dash>('/api/organisations/'+id+'/portal/dashboard'),req<any>('/api/organisations/'+id+'/billing/payments'),req<any>('/api/organisations/'+id+'/kyc')]);setDash(d);setPayments(p);setKyc(k.documents||[])}catch(e){setError(e instanceof Error?e.message:'Could not load organisation data.')}}
 useEffect(()=>{Promise.all([req<any>('/me'),req<any>('/organisations/mine')]).then(([m,o])=>{setCsrf(m.csrf_token||'');if(o.organisations?.[0])setOrgId(o.organisations[0].id)}).catch(e=>setError(e instanceof Error?e.message:'Could not load organisations.'))},[])
 useEffect(()=>{if(orgId)void load(orgId)},[orgId])
 const select=async(o:any)=>{setSelected(o);if(!orgId)return;try{setAnalytics(await req('/api/organisations/'+orgId+'/portal/opportunities/'+o.id+'/analytics'))}catch(e){setError(e instanceof Error?e.message:'Could not load analytics.')}}
 const createCampaign=async()=>{if(!orgId||!sponsor)return;setBusy(true);try{const c:any=await req('/api/organisations/'+orgId+'/discovery/campaigns',{method:'POST',headers:{'X-CSRF-Token':csrf},body:JSON.stringify({name:sponsor.title+' campaign',opportunity_id:sponsor.id,objective:campaignForm.objective,placement:campaignForm.placement,budget_kes:Number(campaignForm.budget),duration_days:Number(campaignForm.duration),target:{active_days:Number(campaignForm.duration)}})});const p:any=await req('/api/organisations/'+orgId+'/discovery/campaigns/'+c.campaign.id+'/payment',{method:'POST',headers:{'X-CSRF-Token':csrf}});if(p.authorization_url)window.location.assign(p.authorization_url);else throw new Error('Payment checkout was not returned.')}catch(e){setError(e instanceof Error?e.message:'Could not start sponsorship.')}finally{setBusy(false)}}
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!orgId)return;setBusy(true);try{const fd=new FormData();fd.append('file',f);fd.append('document_type','organisation_verification');const r=await fetch('/api/organisations/'+orgId+'/kyc/upload',{method:'POST',credentials:'include',headers:{'X-CSRF-Token':csrf},body:fd});const b=await r.json();if(!r.ok)throw new Error(b?.error||'Upload failed');setNotice('Verification document submitted.');await load(orgId)}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false);e.target.value=''}}
 if(!orgId)return <Shell onExit={onExit} title='Organisation Portal'><div style={hero}><h1>Build your student presence.</h1><p>Post opportunities for free, understand performance and sponsor relevant student distribution from one premium workspace.</p></div></Shell>
 if(error)return <Shell onExit={onExit} title={dash?.organisation?.name||'Organisation'}><Card><b>Something needs attention</b><p>{error}</p><button style={btn} onClick={()=>orgId&&load(orgId)}>Retry</button></Card></Shell>
 const totalImp=(dash?.campaigns||[]).reduce((n:number,c:any)=>n+Number(c.delivered_impressions||0),0)
 return <Shell onExit={onExit} title={dash?.organisation?.name||'Organisation'} verified={dash?.organisation?.verification_status==='verified'} tier={dash?.plan?.plan_code}><div style={metrics}><Metric l='Available ad budget' v={money(dash?.ad_budget?.available_minor||0)}/><Metric l='Active sponsorships' v={String(dash?.active_sponsorships||0)}/><Metric l='Campaign impressions' v={totalImp.toLocaleString()}/><Metric l='Opportunity reach' v={selected&&analytics?Number(analytics.organic.reach).toLocaleString():'—'}/></div><nav style={tabs}>{['overview','opportunities','campaigns','billing','verification'].map(x=><button key={x} onClick={()=>setTab(x)} style={{...tabBtn,borderBottom:tab===x?'2px solid '+G:'2px solid transparent'}}>{x}</button>)}</nav>{notice&&<div style={noticeStyle}>{notice}</div>}{sponsor&&<div style={modal}><div style={modalCard}><h3 style={{marginTop:0}}>Sponsor “{sponsor.title}”</h3><p>Choose the campaign objective, placements, budget and maximum delivery window. Prepza controls the underlying billing rules.</p><select value={campaignForm.objective} onChange={e=>setCampaignForm({...campaignForm,objective:e.target.value})} style={input}><option value='reach'>Reach</option><option value='traffic'>Traffic</option><option value='applications'>Applications</option></select><select value={campaignForm.placement} onChange={e=>setCampaignForm({...campaignForm,placement:e.target.value})} style={input}><option value='feed'>Opportunities feed</option><option value='push'>Targeted push</option><option value='feed_push'>Feed + push</option></select><input type='number' min='5000' step='500' value={campaignForm.budget} onChange={e=>setCampaignForm({...campaignForm,budget:e.target.value})} style={input}/><select value={campaignForm.duration} onChange={e=>setCampaignForm({...campaignForm,duration:e.target.value})} style={input}><option value='7'>7-day maximum window</option><option value='30'>30-day maximum window</option><option value='90'>90-day maximum window</option></select><p>Billing is prepaid. Qualifying impressions, clicks and successful push deliveries are metered according to the selected placement rules. Processing fees are separate from campaign value.</p><div style={{display:'flex',gap:8}}><button style={btn} disabled={busy} onClick={createCampaign}>{busy?'Opening…':'Review & pay'}</button><button style={cancelBtn} onClick={()=>setSponsor(null)}>Cancel</button></div></div></div>}}{tab==='overview'&&<Overview dash={dash} select={select}/>} {tab==='opportunities'&&<OpportunityList dash={dash} select={select} selected={selected} analytics={analytics} onSponsor={setSponsor}/>}  {tab==='campaigns'&&<Campaigns dash={dash}/>} {tab==='billing'&&<Billing orgId={orgId} data={payments}/>} {tab==='verification'&&<Verification org={dash?.organisation} docs={kyc} busy={busy} upload={upload}/>}</Shell>
}
function Shell(p:any){return <div style={{height:'100dvh',display:'flex',flexDirection:'column',background:BG,fontFamily:'Plus Jakarta Sans',color:N}}><header style={{background:'linear-gradient(120deg,'+N+',#182A59)',color:'#fff',padding:18,display:'flex',alignItems:'center',gap:12}}><button onClick={p.onExit} style={icon}>←</button><div style={{flex:1}}><small>PREPZA BUSINESS</small><div style={{fontSize:18,fontWeight:850}}>{p.title}</div></div>{p.verified&&<span style={badge}>VERIFIED</span>}{p.tier&&<span style={badge}>{String(p.tier).toUpperCase()}</span>}</header><main style={{flex:1,overflowY:'auto',padding:16,maxWidth:1050,width:'100%',boxSizing:'border-box',margin:'0 auto'}}>{p.children}</main></div>}
function Metric(p:any){return <Card><small>{p.l}</small><div style={{fontSize:23,fontWeight:850,color:p.l==='Available ad budget'?G:N,marginTop:5}}>{p.v}</div></Card>}
function Overview({dash,select}:any){return <div style={stack}><div style={hero}><small>BUSINESS OVERVIEW</small><h1>Your opportunities, in one place.</h1><p>Organic posting is free. Sponsorship adds paid distribution. Campaigns control budget, audience, placements and maximum delivery window.</p></div><Card><h3>Active sponsorships</h3>{dash?.campaigns?.filter((c:any)=>['active','paused'].includes(c.status)).map((c:any)=><div key={c.id} style={row} onClick={()=>select(dash.opportunities.find((o:any)=>o.id===c.opportunity_id))}><div style={{flex:1}}><b>{c.opportunity_title}</b><small>{c.name} · {c.placement}</small></div><b>{Number(c.delivered_impressions).toLocaleString()}</b></div>)||<Empty text='No active sponsorships yet.'/>}</Card><Card><h3>Recent opportunities</h3>{dash?.opportunities?.slice(0,6).map((o:any)=><div key={o.id} style={row} onClick={()=>select(o)}><div style={{flex:1}}><b>{o.title}</b><small>{o.status} · {Number(o.view_count).toLocaleString()} total views</small></div><span style={pill(o.organic_free_cap_reached_at?'CAPPED':'FREE')}>{o.organic_free_cap_reached_at?'CAPPED':'FREE'}</span></div>)}</Card></div>}
function OpportunityList({dash,select,selected,analytics,onSponsor}:any){return <div style={stack}><Card><h3>My opportunities</h3><p>Every opportunity gets its own analytics. Organic distribution is free up to 5,000 qualifying views, with at most 3 free views per student.</p>{dash?.opportunities?.map((o:any)=><div key={o.id} style={row} onClick={()=>select(o)}><div style={{flex:1}}><b>{o.title}</b><small>{o.status} · organic {Number(o.view_count).toLocaleString()} views · sponsored {Number(o.sponsored_impressions).toLocaleString()} impressions</small></div><span style={pill(o.status.toUpperCase())}>{o.status}</span>{o.status==='published'&&<button style={miniBtn} onClick={(e)=>{e.stopPropagation();onSponsor(o)}}>Sponsor</button>}</div>)}</Card>{selected&&analytics&&<Card><h3>{selected.title} · Analytics</h3><div style={metrics}><Metric l='Organic impressions' v={Number(analytics.organic.impressions).toLocaleString()}/><Metric l='Organic reach' v={Number(analytics.organic.reach).toLocaleString()}/><Metric l='Sponsored impressions' v={Number(analytics.sponsored.impressions).toLocaleString()}/><Metric l='Applications' v={Number(analytics.sponsored.applications).toLocaleString()}/></div><p>Campaign performance is nested under this opportunity; reach remains opportunity-level.</p></Card>}</div>}
function Campaigns({dash}:any){return <div style={stack}><Card><h3>Campaigns</h3><p>A campaign is a paid delivery programme attached to a sponsorship. It has its own budget, audience, placements and 7, 30 or 90-day maximum delivery window.</p>{dash?.campaigns?.map((c:any)=><div key={c.id} style={row}><div style={{flex:1}}><b>{c.name}</b><small>{c.opportunity_title} · {c.objective} · {c.placement}</small></div><span style={pill(c.status.toUpperCase())}>{c.status}</span></div>)}</Card></div>}
function Billing({orgId,data}:any){return <div style={stack}><Card><h3>Billing & receipts</h3><p>Paystack and bank/invoice payments are recorded separately from campaign value. Every completed payment has a downloadable Prepza receipt.</p>{data.payments?.map((p:any)=><div key={p.id} style={row}><div style={{flex:1}}><b>{p.provider_reference}</b><small>{p.provider} · {p.status}</small></div><b>{money(p.customer_amount_minor)}</b><a href={'/api/organisations/'+orgId+'/billing/payments/'+p.id+'/receipt.pdf'} style={link}>Receipt PDF</a></div>)}{data.invoices?.map((i:any)=><div key={i.id} style={row}><div style={{flex:1}}><b>{i.invoice_number}</b><small>{i.status} · bank transfer</small></div><b>{money(i.total_minor)}</b><a href={'/api/organisations/'+orgId+'/billing/invoices/'+i.id+'/receipt.pdf'} style={link}>Invoice PDF</a></div>)}{!data.payments?.length&&!data.invoices?.length&&<Empty text='No billing records yet.'/>}</Card></div>}
function Verification({org,docs,busy,upload}:any){return <div style={stack}><Card><h3>Organisation verification</h3><span style={pill(String(org?.verification_status||'pending').toUpperCase())}>{org?.verification_status||'pending'}</span><p>{org?.verification_notes||'Paid campaign activation requires a verified organisation.'}</p><label style={btnLabel}>Upload verification document<input hidden type='file' accept='.pdf,.png,.jpg,.jpeg' disabled={busy} onChange={upload}/></label></Card><Card><h3>Submitted documents</h3>{docs.map((d:any)=><div key={d.id} style={row}><div style={{flex:1}}><b>{d.file_name}</b><small>{d.document_type}</small></div><span style={pill(String(d.status).toUpperCase())}>{d.status}</span></div>)}{!docs.length&&<Empty text='No documents submitted yet.'/>}</Card></div>}
function Card(p:any){return <section style={card}>{p.children}</section>}
function Empty({text}:any){return <div style={{padding:18,textAlign:'center',color:M,fontSize:12}}>{text}</div>}
const miniBtn:React.CSSProperties={border:0,borderRadius:9,padding:'7px 9px',background:'#EEF1F7',color:N,fontSize:10,fontWeight:850,cursor:'pointer'}
const cancelBtn:React.CSSProperties={border:0,borderRadius:11,padding:'10px 14px',fontWeight:800,background:'#EEF0F4',color:N}
const modal:React.CSSProperties={position:'fixed',inset:0,background:'rgba(7,13,31,.55)',display:'flex',alignItems:'flex-end',justifyContent:'center',zIndex:300}
const modalCard:React.CSSProperties={background:'#fff',width:'min(620px,100%)',borderRadius:'22px 22px 0 0',padding:22,boxSizing:'border-box',boxShadow:'0 -10px 40px rgba(0,0,0,.2)'}
const stack:React.CSSProperties={display:'grid',gap:14},metrics:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10},tabs:React.CSSProperties={display:'flex',gap:18,overflowX:'auto',borderBottom:'1px solid #E2E5EC',margin:'14px 0',paddingBottom:0},tabBtn:React.CSSProperties={border:0,background:'transparent',padding:'10px 2px',fontSize:11,fontWeight:850,cursor:'pointer',textTransform:'capitalize',fontFamily:'inherit'},card:React.CSSProperties={background:'#fff',border:'1px solid #E7E9EF',borderRadius:18,padding:17,boxShadow:'0 5px 20px rgba(11,20,55,.05)'},hero:React.CSSProperties={background:'linear-gradient(125deg,'+N+',#182A59)',color:'#fff',borderRadius:22,padding:22},row:React.CSSProperties={display:'flex',alignItems:'center',gap:12,borderTop:'1px solid #EEF0F4',padding:'13px 0',cursor:'pointer'},badge:React.CSSProperties={fontSize:9,fontWeight:850,letterSpacing:.6,padding:'5px 8px',borderRadius:99,background:'rgba(201,168,76,.16)',color:'#E8C97E'},icon:React.CSSProperties={width:34,height:34,border:0,borderRadius:10,background:'rgba(255,255,255,.1)',color:'#fff',fontSize:18},link:React.CSSProperties={fontSize:10,fontWeight:850,color:'#5570B7',textDecoration:'none'},btn:React.CSSProperties={background:G,color:N,border:0,borderRadius:11,padding:'10px 14px',fontWeight:850},btnLabel:React.CSSProperties={display:'inline-block',background:G,color:N,borderRadius:11,padding:'10px 14px',fontWeight:850,cursor:'pointer'},noticeStyle:React.CSSProperties={background:'#EDF8F2',border:'1px solid #CBEBD9',color:'#176A46',borderRadius:12,padding:10,fontSize:11},pill=(x:string):React.CSSProperties=>({fontSize:9,fontWeight:850,padding:'4px 7px',borderRadius:99,background:'#F1F3F7',color:N})
